version: '3.7'

services:
  db:
    image: postgres
    container_name: kryptokrona_api_db
    restart: always
    environment:
      POSTGRES_DB: kryptokrona_api_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test1234
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - kryptokrona_api_net

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    command: --defaults-file /liquibase/liquibase.properties --changeLogFile=db/changelog/master.xml update
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/db/changelog
      - ./liquibase.properties:/liquibase/liquibase.properties
    depends_on:
      - db
    networks:
      - kryptokrona_api_net

  monitor:
    build: monitor
    container_name: kryptokrona_api_monitor
    environment:
     PRIVATE_GITHUB_TOKEN: change-me
    ports:
      - "3000:3000"
    networks:
      - kryptokrona_api_net

  backend:
    build: .
    container_name: kryptokrona_api_backend
    ports:
      - "8080:8080"
    networks:
      - kryptokrona_api_net

  prometheus:
    image: prom/prometheus:latest
    container_name: kryptokrona_api_prometheus
    ports:
      - "9090:9090"

volumes:
  db:

networks:
  kryptokrona_api_net:
    driver: bridge