openapi: 3.0.3
info:
  title: Kryptokrona API
  description: Kryptokrona API for obtaining cached data from the Kryptokrona Blockchain.
  version: 0.1.0
  contact:
    name: Marcus Cvjeticanin
    url: https://github.com/mjovanc
    email: mjovanc@icloud.com
  license:
    name: The 3-Clause BSD License
    url: https://github.com/kryptokrona/kryptokrona-api/blob/master/LICENSE
servers:
- url: https://api.mjovanc.com
  description: Kryptokrona API Main Server
- url: https://test-api.mjovanc.com
  description: Kryptokrona API Staging Server
- url: http://localhost:8080
  description: Kryptokrona API Development Server
paths:
  
