spring:
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOSTNAME:localhost}:${POSTGRESQL_PORT:5433}/${POSTGRESQL_DB_NAME:kryptokrona_api_test}
    username: ${POSTGRESQL_DB_USER:postgres}
    password: ${POSTGRESQL_DB_PASSWORD:test1234}
  liquibase:
    changeLog: "classpath:db/changelog/master.xml"

apiServerUrl: ${SYS_API_SERVER_URL}