---
- name: Start Kryptokrona Monitor Container
  docker_container:
    name: "{{ docker_container_name_monitor }}"
    image: "{{ docker_image_monitor }}:latest"
    state: started
    pull: true
    force_kill: yes
    recreate: yes
    env: {
      PRIVATE_GITHUB_TOKEN: "{{ vault_github_token }}",
      ORIGIN: "https://{{ domain_name }}/monitor"
    }
    networks:
      - name: "host"