---
- name: Start Kryptokrona API Container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_backend }}:latest"
    state: started
    pull: true
    force_kill: yes
    recreate: yes
    env: {
      DB_URL: "jdbc:postgresql://127.0.0.1:5432/kryptokrona_api_dev",
      DB_USER: "{{ vault_postgres_db_user }}",
      DB_PASSWORD: "{{ vault_postgres_db_password }}",
    }
    networks:
      - name: "host"