---
- hosts: vps
  remote_user: root
  become: true
  gather_facts: yes
  vars:
    kryptokrona_api_name: kryptokrona_api

    # Docker GitHub Container Registry
    docker_image: "ghcr.io/mjovanc/kryptokrona-api"

    # A list of users who will be added to the docker group.
    docker_users: [
      "kryptokrona_docker"
    ]

    docker_container_name: kryptokrona-api
    docker_network_name: kryptokrona

    # Docker daemon options as a dict
    docker_daemon_options: { }

    # Prometheus configuration
    prometheus_targets:
      node:
      - targets:
        - "{{ domain_name }}:9100"
        labels:
          env: prod

    node_exporter_version: "{{ exporter_version }}"

    website_name: kryptokrona_api
    web_server_ip: "{{ domain_name }}"
    web_server_port: "443"
    hidden_service_port: "443"

    # DO NOT CONFIGURE THE ABOVE YOURSELF
    sys_api_title: "Kryptokrona API"
    sys_api_description: "Kryptokrona API in Java for obtaining cached data from the Kryptokrona Blockchain."
    sys_api_contact_name: "Marcus Cvjeticanin"
    sys_api_contact_email: "mjovanc@icloud.com"
    sys_api_contact_url: "https://github.com/mjovanc/kryptokrona-api"

  roles:
  #- base
  - postgres
  - docker
  - nginx
  - prometheus
  - onion
