---
- hosts: vps
  remote_user: root
  become: true
  gather_facts: yes
  vars:
    ansible_forks: 1
    ansible_python_interpreter: /usr/bin/python3
    kryptokrona_api_name: kryptokrona_api

    # Docker GitHub Container Registry
    docker_image_backend: "ghcr.io/kryptokrona/kryptokrona-api"
    docker_image_monitor: "ghcr.io/kryptokrona/kryptokrona-api-monitor"

    # A list of users who will be added to the docker group.
    docker_users: [
      "kryptokrona_docker"
    ]

    docker_container_name: kryptokrona-api
    docker_container_name_monitor: kryptokrona-monitor
    docker_network_name: kryptokrona

    # Docker daemon options as a dict
    docker_daemon_options: { }

    # Prometheus configuration
    prometheus_targets:
      node:
      - targets:
        - "{{ domain_name }}:9100"
        labels:
          env: prod

    node_exporter_version: "{{ exporter_version }}"

    website_name: kryptokrona_api
    web_server_ip: "{{ domain_name }}"
    web_server_port: "443"
    hidden_service_port: "443"

  roles:
  #- base
  - postgres
  - docker
  - liquibase
  - backend
  - monitor
  - nginx
  - prometheus
  - onion
