name: Deploy to Staging & Production

on:
  push:
    branches:
      - master

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit

  # frontend: TODO: (we will have some sort of gui to display the data etc)


#  staging-deploy:
#    name: Deploy Staging
#    runs-on: ubuntu-latest
#    needs: docker
#
#    steps:
#      - name: Check out the codebase.
#        uses: actions/checkout@v2
#
#      - name: Run playbook
#        uses: dawidd6/action-ansible-playbook@v2
#        with:
#          playbook: provision_vps.yml
#          directory: ./ansible
#          key: ${{secrets.ANSIBLE_PRIVATE_KEY}}
#          vault_password: ${{secrets.ANSIBLE_VAULT_PASS}}
#          options: |
#            --inventory staging.inventory
#            --verbose
#
#  smoke-test-staging:
#    name: Smoke Test Staging
#    runs-on: ubuntu-latest
#    needs: [ staging-deploy ]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Uses Python 3.11
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.11.0-alpha.1'
#
#      - name: Smoke Test
#        run: |
#          pip3 install requests
#          python3 scripts/tests/kryptokrona-api/smoke-test.py test-api.mjovanc.com
#
#  deploy-prod:
#    name: Deploy Prod
#    runs-on: ubuntu-latest
#    needs: [ smoke-test-staging ]
#
#    steps:
#      - name: Check out the codebase.
#        uses: actions/checkout@v2
#
#      - name: Run playbook
#        uses: dawidd6/action-ansible-playbook@v2
#        with:
#          playbook: provision_vps.yml
#          directory: ./ansible
#          key: ${{secrets.ANSIBLE_PRIVATE_KEY}}
#          vault_password: ${{secrets.ANSIBLE_VAULT_PASS}}
#          options: |
#            --inventory prod.inventory
#            --verbose
#
#  smoke-test-prod:
#    name: Smoke Test Prod
#    runs-on: ubuntu-latest
#    needs: [ deploy-prod ]
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Uses Python 3.11
#        uses: actions/setup-python@v3
#        with:
#          python-version: '3.11.0-alpha.1'
#
#      - name: Smoke Test
#        run: |
#          pip3 install requests
#          python3 scripts/tests/kryptokrona-api/smoke-test.py api.mjovanc.com